apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/WebCBIR"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cbir
spec:
  replicas: 4
  selector:
    matchLabels:
      name: cbir
  template:
    metadata:
      name: cbir
      labels:
        name: cbir
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim
      containers:
        - name: cbir
          image: leon0408/cbir
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/app"
              name: task-pv-storage
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 900Mi

---
apiVersion: v1
kind: Service
metadata:
  name: cbir-service
spec:
  type: LoadBalancer
  selector:
    name: cbir
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
