FROM ubuntu:18.04
RUN mkdir app
COPY requirements.txt /app
WORKDIR /app
RUN apt update && apt upgrade -y
RUN apt install python3 python3-pip -y
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt
CMD ["python3", "runner.py"]
